### ISSUE TITLE
Copying profile overwrites existing or default profile

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.twingle#29] opened 2020-06-15 14:30 UTC
If you create a new profile (``1.2-beta1``) the settings always overwrite the default project.

**Comment by jensschuppe** [comment] 2020-10-28 10:14
I could not reproduce that, but noticed that when storing many profiles, a "Data too long" error occurs (at least since one of the recent CivICRM versions, whereas before, data would have simply got cut off), see #42.

I suppose that overwriting something else might be a side effect of that.

**Comment by jensschuppe** [comment] 2020-11-10 09:36
This is valid. The default profile is being overwritten when a profile is copied, then saved.

**Comment by jensschuppe** [comment] 2020-11-10 10:34
This stems from `CRM_Utils_Request::retrieve('name', 'String', $this)` retrieving from `GET` values when the form is loaded, but from `POST` when it is saved, using the new name for the latter, for which no profile exists and therefore the default profile is being used for storing.

The Copy action now uses a different parameter for the source profile and also validates new profile names.

**Comment by jensschuppe** [comment] 2020-11-10 10:37
This needs to be merged both into `master` and `1.2.x` branches, once it is successfully tested.

**Comment by jensschuppe** [comment] 2020-11-10 11:20
This has positive test feedback and will be released with `1.2`

**Closed by jensschuppe** 2020-11-10 11:20 UTC
Labels: bug
